@startuml
class Framework.BinarySearch {
# boolean isSimple(Problem)
# Solution simplySolve(Problem)
# Problem[] decompose(Problem)
# Solution combine(Problem,Solution[])
}
interface Framework.Solution {
}
interface Framework.Problem {
}
abstract class Framework.DivConqTemplate {
+ Solution solve(Problem)
# {abstract}boolean isSimple(Problem)
# {abstract}Solution simplySolve(Problem)
# {abstract}Problem[] decompose(Problem)
# {abstract}Solution combine(Problem,Solution[])
}


Framework.DivConqTemplate <|-- Framework.BinarySearch
@enduml